#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}/kgs-calendar"
SERVICE_ACCOUNT_TARGET="$CONFIG_HOME/google-play-service-account.json"
KEYSTORE_TARGET="$CONFIG_HOME/upload-keystore.jks"
PUBLISHER_CONFIG="$CONFIG_HOME/publisher-config.json"

banner "KGS Calendar · local Google Play publishing"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Google Cloud — API and service account"
say "Create a dedicated machine identity for Google Play publishing."
open_url "https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com"
step "Select an existing Google Cloud project or create a dedicated one."
step "On the Google Play Android Developer API page, click Enable."
pause "Press Enter after the API shows as enabled."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts"
step "Click Create service account. Name it kgs-calendar-play-publisher."
step "Do not grant it a Google Cloud project role; click Done. Play permissions come later."
step "Open it, then Keys → Add key → Create new key → JSON."
step "The browser downloads a JSON file. Keep that file private."
ask SERVICE_ACCOUNT_SOURCE "Path to the downloaded JSON file:"
SERVICE_ACCOUNT_SOURCE="${SERVICE_ACCOUNT_SOURCE/#\~/$HOME}"
[[ -f "$SERVICE_ACCOUNT_SOURCE" ]] || { warn "file not found: $SERVICE_ACCOUNT_SOURCE"; exit 1; }
SERVICE_ACCOUNT_EMAIL=$(python3 - "$SERVICE_ACCOUNT_SOURCE" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
data = json.loads(path.read_text(encoding="utf-8"))
if data.get("type") != "service_account" or not data.get("client_email") or not data.get("private_key"):
    raise SystemExit("That is not a valid service-account JSON key")
print(data["client_email"])
PY
)
install -d -m 700 "$CONFIG_HOME"
if [[ -e "$SERVICE_ACCOUNT_TARGET" ]]; then
  confirm "Replace the existing local service-account key?" || exit 1
fi
install -m 600 "$SERVICE_ACCOUNT_SOURCE" "$SERVICE_ACCOUNT_TARGET"
say "Service account: $SERVICE_ACCOUNT_EMAIL"
warn "Delete the original JSON from Downloads after this wizard succeeds."
pause "Press Enter to continue."

stage "Google Play Console — app permission"
say "Give the service account access only to KGS Calendar's testing releases."
open_url "https://play.google.com/console/developers"
step "Open your developer account, then Users and permissions."
step "Click Invite new users and enter: $SERVICE_ACCOUNT_EMAIL"
step "Under App permissions, add KGS Calendar (com.kgs501.kgscalendar)."
step "Grant Release apps to testing tracks. Do not grant production or financial permissions."
step "Click Invite user. A service account does not need to accept an email invitation."
note "New Play permissions can take a few minutes to propagate."
pause "Press Enter after the service account appears in Users and permissions."

stage "This machine — upload signing key"
say "An upload keystore contains the private key that identifies app updates to Google Play."
if confirm "Do you have the existing upload .jks/.keystore and its passwords?"; then
  ask KEYSTORE_SOURCE "Path to the existing upload .jks/.keystore file:"
  KEYSTORE_SOURCE="${KEYSTORE_SOURCE/#\~/$HOME}"
  [[ -f "$KEYSTORE_SOURCE" ]] || { warn "file not found: $KEYSTORE_SOURCE"; exit 1; }
  ask KEY_ALIAS "Key alias:"
  ask_secret KEYSTORE_PASSWORD "Keystore password:"
  ask_secret KEY_PASSWORD "Key password:"
  export KGS_SETUP_STORE_PASSWORD="$KEYSTORE_PASSWORD"
  if ! keytool -list -keystore "$KEYSTORE_SOURCE" -alias "$KEY_ALIAS" \
      -storepass:env KGS_SETUP_STORE_PASSWORD >/dev/null 2>&1; then
    unset KGS_SETUP_STORE_PASSWORD
    warn "The keystore password or key alias is not valid."
    exit 1
  fi
  unset KGS_SETUP_STORE_PASSWORD
  if [[ -e "$KEYSTORE_TARGET" ]]; then
    confirm "Replace the existing local upload keystore?" || exit 1
  fi
  install -m 600 "$KEYSTORE_SOURCE" "$KEYSTORE_TARGET"
else
  say "No existing upload key was found. The wizard will generate a dedicated replacement."
  confirm "Generate a new KGS Calendar upload key on this machine?" || exit 1
  if [[ -e "$KEYSTORE_TARGET" ]]; then
    confirm "Replace the existing local upload keystore?" || exit 1
  fi
  KEY_ALIAS="upload"
  KEYSTORE_PASSWORD=$(openssl rand -hex 24)
  KEY_PASSWORD=$(openssl rand -hex 24)
  KEYGEN_DIR=$(mktemp -d "$CONFIG_HOME/.upload-key.XXXXXX")
  KEYGEN_KEYSTORE="$KEYGEN_DIR/upload-keystore.jks"
  export KGS_SETUP_STORE_PASSWORD="$KEYSTORE_PASSWORD"
  export KGS_SETUP_KEY_PASSWORD="$KEY_PASSWORD"
  keytool -genkeypair \
    -keystore "$KEYGEN_KEYSTORE" \
    -storetype JKS \
    -alias "$KEY_ALIAS" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10000 \
    -dname "CN=KGS Calendar Upload" \
    -storepass:env KGS_SETUP_STORE_PASSWORD \
    -keypass:env KGS_SETUP_KEY_PASSWORD >/dev/null 2>&1
  mv "$KEYGEN_KEYSTORE" "$KEYSTORE_TARGET"
  rmdir "$KEYGEN_DIR"
  chmod 600 "$KEYSTORE_TARGET"
  keytool -export -rfc \
    -keystore "$KEYSTORE_TARGET" \
    -alias "$KEY_ALIAS" \
    -file "$CONFIG_HOME/upload_certificate.pem" \
    -storepass:env KGS_SETUP_STORE_PASSWORD >/dev/null 2>&1
  chmod 644 "$CONFIG_HOME/upload_certificate.pem"
  unset KGS_SETUP_STORE_PASSWORD KGS_SETUP_KEY_PASSWORD
  say "Generated the private upload key at $KEYSTORE_TARGET."
  say "Generated its public certificate at $CONFIG_HOME/upload_certificate.pem."
  if confirm "Has any KGS Calendar bundle already been uploaded to Google Play?"; then
    say "Google Play must approve this new upload key before it can sign another release."
    open_url "https://play.google.com/console/developers"
    step "Select KGS Calendar, then open App integrity / Manage Play app signing."
    step "In Upload key certificate, click Request upload key reset."
    step "Choose the lost-key reason and upload: $CONFIG_HOME/upload_certificate.pem"
    step "Submit the request and wait for Google's email stating when the new key becomes valid."
    pause "Press Enter after the reset request has been submitted."
  else
    note "For a first-ever bundle upload, the new key can be used without a reset."
  fi
fi
export KGS_SETUP_CONFIG="$PUBLISHER_CONFIG"
export KGS_SETUP_SERVICE_ACCOUNT="$SERVICE_ACCOUNT_TARGET"
export KGS_SETUP_KEYSTORE="$KEYSTORE_TARGET"
export KGS_SETUP_KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD"
export KGS_SETUP_KEY_ALIAS="$KEY_ALIAS"
export KGS_SETUP_KEY_PASSWORD="$KEY_PASSWORD"
python3 <<'PY'
import json
import os
import pathlib

config = {
    "package_name": "com.kgs501.kgscalendar",
    "service_account_file": os.environ["KGS_SETUP_SERVICE_ACCOUNT"],
    "keystore_file": os.environ["KGS_SETUP_KEYSTORE"],
    "keystore_password": os.environ["KGS_SETUP_KEYSTORE_PASSWORD"],
    "key_alias": os.environ["KGS_SETUP_KEY_ALIAS"],
    "key_password": os.environ["KGS_SETUP_KEY_PASSWORD"],
}
path = pathlib.Path(os.environ["KGS_SETUP_CONFIG"])
path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
path.chmod(0o600)
PY
unset KGS_SETUP_CONFIG KGS_SETUP_SERVICE_ACCOUNT KGS_SETUP_KEYSTORE
unset KGS_SETUP_KEYSTORE_PASSWORD KGS_SETUP_KEY_ALIAS KGS_SETUP_KEY_PASSWORD
unset KEYSTORE_PASSWORD KEY_PASSWORD
say "Stored the local publisher config at $PUBLISHER_CONFIG (mode 600)."
pause "Press Enter to continue."

stage "Verify — signed build and Play access"
say "This builds a signed AAB and creates then deletes an empty Play edit."
say "It does not upload a bundle or publish a release."
if confirm "Run the non-publishing verification now?"; then
  cd "$REPO_ROOT"
  python3 tools/play_publisher.py verify
else
  SKIPPED+=("verification: python3 tools/play_publisher.py verify")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
